//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hured
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HuredEntities1 : DbContext
    {
        public HuredEntities1()
            : base("name=HuredEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<Адреса> Адреса { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Подразделения> Подразделения { get; set; }
        public virtual DbSet<ПриказыКомандировка> ПриказыКомандировка { get; set; }
        public virtual DbSet<ПриказыОтпуск> ПриказыОтпуск { get; set; }
        public virtual DbSet<ПриказыПриёма> ПриказыПриёма { get; set; }
        public virtual DbSet<ПриказыУвольнение> ПриказыУвольнение { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<СписокВоинскогоУчёта> СписокВоинскогоУчёта { get; set; }
        public virtual DbSet<СписокДополнительнойИнформации> СписокДополнительнойИнформации { get; set; }
        public virtual DbSet<СписокОбразований> СписокОбразований { get; set; }
        public virtual DbSet<СписокОсновнойИнформации> СписокОсновнойИнформации { get; set; }
        public virtual DbSet<Статусы> Статусы { get; set; }
        public virtual DbSet<ТабельныеЗаписи> ТабельныеЗаписи { get; set; }
        public virtual DbSet<УдостоверенияЛичности> УдостоверенияЛичности { get; set; }
        public virtual DbSet<УчётнаяЗапись> УчётнаяЗапись { get; set; }
    }
}
