//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hured
{
    using System;
    using System.Collections.Generic;
    
    public partial class Должности
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Должности()
        {
            this.СписокОсновнойИнформации = new HashSet<СписокОсновнойИнформации>();
            this.ПриказыПриёма = new HashSet<ПриказыПриёма>();
        }
    
        public int ДолжностьId { get; set; }
        public string Название { get; set; }
        public string Расписание { get; set; }
        public Nullable<int> Подразделение_ПодразделениеId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписокОсновнойИнформации> СписокОсновнойИнформации { get; set; }
        public virtual Подразделения Подразделения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПриказыПриёма> ПриказыПриёма { get; set; }
    }
}
