//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hured
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПриказыУвольнение
    {
        public int ПриказУвольнениеId { get; set; }
        public string Номер { get; set; }
        public System.DateTime Дата { get; set; }
        public string Основание { get; set; }
        public string ОснованиеДокумент { get; set; }
        public string НомерТрудовогоДоговора { get; set; }
        public System.DateTime ДатаТрудовогоДоговора { get; set; }
        public System.DateTime ДатаУвольнения { get; set; }
        public Nullable<int> Сотрудник_СотрудникId { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
