//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hured
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПриказыКомандировка
    {
        public int ПриказКомандировкаId { get; set; }
        public string Номер { get; set; }
        public System.DateTime Дата { get; set; }
        public string Место { get; set; }
        public System.DateTime НачалоКомандировки { get; set; }
        public System.DateTime КонецКомандировки { get; set; }
        public string Цель { get; set; }
        public string Основание { get; set; }
        public string ЗаСчёт { get; set; }
        public Nullable<int> Сотрудник_СотрудникId { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
