//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hured
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПриказыПриёма
    {
        public int ПриказПриёмId { get; set; }
        public string Номер { get; set; }
        public System.DateTime Дата { get; set; }
        public System.DateTime НачалоРаботы { get; set; }
        public System.DateTime КонецРаботы { get; set; }
        public bool ИспытательныйСрок { get; set; }
        public string ИспытательныйСрокДлительность { get; set; }
        public string Оклад { get; set; }
        public string Надбавка { get; set; }
        public string Примечания { get; set; }
        public string НомерТрудовогоДоговора { get; set; }
        public System.DateTime ДатаТрудовогоДоговора { get; set; }
        public Nullable<int> Должность_ДолжностьId { get; set; }
        public Nullable<int> Сотрудник_СотрудникId { get; set; }
    
        public virtual Должности Должности { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
