//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hured
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.ПриказыКомандировка = new HashSet<ПриказыКомандировка>();
            this.ПриказыОтпуск = new HashSet<ПриказыОтпуск>();
            this.ПриказыПриёма = new HashSet<ПриказыПриёма>();
            this.ПриказыУвольнение = new HashSet<ПриказыУвольнение>();
            this.СписокОбразований = new HashSet<СписокОбразований>();
            this.ТабельныеЗаписи = new HashSet<ТабельныеЗаписи>();
        }
    
        public int СотрудникId { get; set; }
        public Nullable<int> ВоинскийУчёт_ВоинскийУчётId { get; set; }
        public Nullable<int> ДополнительнаяИнформация_ДополнительнаяИнформацияId { get; set; }
        public Nullable<int> ОсновнаяИнформация_ОсновнаяИнформацияId { get; set; }
        public Nullable<int> УдостоверениеЛичности_УдостоверениеЛичностиId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПриказыКомандировка> ПриказыКомандировка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПриказыОтпуск> ПриказыОтпуск { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПриказыПриёма> ПриказыПриёма { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПриказыУвольнение> ПриказыУвольнение { get; set; }
        public virtual СписокОсновнойИнформации СписокОсновнойИнформации { get; set; }
        public virtual УдостоверенияЛичности УдостоверенияЛичности { get; set; }
        public virtual СписокДополнительнойИнформации СписокДополнительнойИнформации { get; set; }
        public virtual СписокВоинскогоУчёта СписокВоинскогоУчёта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписокОбразований> СписокОбразований { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТабельныеЗаписи> ТабельныеЗаписи { get; set; }
    }
}
