//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hured
{
    using System;
    using System.Collections.Generic;
    
    public partial class СписокОбразований
    {
        public int ОбразованиеId { get; set; }
        public string Тип { get; set; }
        public string Учреждение { get; set; }
        public string Дополнительно { get; set; }
        public string Документ { get; set; }
        public System.DateTime НачалоОбучения { get; set; }
        public System.DateTime КонецОбучения { get; set; }
        public string Серия { get; set; }
        public string Номер { get; set; }
        public string Специальность { get; set; }
        public string Квалификация { get; set; }
        public Nullable<int> Сотрудник_СотрудникId { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
