//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hured
{
    using System;
    using System.Collections.Generic;
    
    public partial class СписокВоинскогоУчёта
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public СписокВоинскогоУчёта()
        {
            this.Сотрудники = new HashSet<Сотрудники>();
        }
    
        public int ВоинскийУчётId { get; set; }
        public string КатегорияЗапаса { get; set; }
        public string Звание { get; set; }
        public string Профиль { get; set; }
        public string КодВус { get; set; }
        public string КатегорияГодности { get; set; }
        public string НаименованиеВоенкомата { get; set; }
        public string СостоитНаУчете { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудники> Сотрудники { get; set; }
    }
}
