//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hured
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТабельныеЗаписи
    {
        public int ТабельнаяЗаписьId { get; set; }
        public System.DateTime Дата { get; set; }
        public string Часы { get; set; }
        public string Примечание { get; set; }
        public Nullable<int> Сотрудник_СотрудникId { get; set; }
        public Nullable<int> Статус_СтатусId { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Статусы Статусы { get; set; }
    }
}
