//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hured
{
    using System;
    using System.Collections.Generic;
    
    public partial class УдостоверенияЛичности
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public УдостоверенияЛичности()
        {
            this.Сотрудники = new HashSet<Сотрудники>();
        }
    
        public int УдостоверениеЛичностиId { get; set; }
        public string Серия { get; set; }
        public string Номер { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public string МестоРождения { get; set; }
        public string КемВыдан { get; set; }
        public System.DateTime КогдаВыдан { get; set; }
        public Nullable<int> Прописка_АдресId { get; set; }
        public Nullable<int> ФактическоеМестоЖительства_АдресId { get; set; }
    
        public virtual Адреса Адреса { get; set; }
        public virtual Адреса Адреса1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудники> Сотрудники { get; set; }
    }
}
